-- =====================================================
-- 夫婦畑日記 - Supabase テーブル設計
-- =====================================================

-- 1. posts テーブルの作成
-- 投稿データを管理するメインテーブル
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  author TEXT NOT NULL CHECK (author IN ('father', 'mother')),
  comment TEXT,
  image_url TEXT,
  is_deleted BOOLEAN DEFAULT false NOT NULL,
  
  -- 同じ日に同じ投稿者は1回のみ投稿可能
  CONSTRAINT unique_post_per_day UNIQUE (date, author)
);

-- 2. インデックスの作成
-- 日付での検索を高速化
CREATE INDEX idx_posts_date ON posts(date DESC);

-- 投稿者での検索を高速化
CREATE INDEX idx_posts_author ON posts(author);

-- 論理削除フラグでの絞り込みを高速化
CREATE INDEX idx_posts_is_deleted ON posts(is_deleted);

-- 3. Row Level Security (RLS) の有効化
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- 4. RLS ポリシーの作成
-- 誰でも読み取り可能（削除されていない投稿のみ）
CREATE POLICY "Enable read access for all users" ON posts
AS PERMISSIVE FOR SELECT
TO public
USING (is_deleted = false);

-- 誰でも新規投稿可能
CREATE POLICY "Enable insert for all users" ON posts
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

-- 誰でも更新可能（削除されていない投稿のみ）
CREATE POLICY "Enable update for all users" ON posts
AS PERMISSIVE FOR UPDATE
TO public
USING (is_deleted = false)
WITH CHECK (true);

-- =====================================================
-- Storage の設定（Supabase管理画面から実行）
-- =====================================================
-- 
-- 1. Storage > New bucket で「images」という名前のバケットを作成
-- 2. 「Public bucket」にチェックを入れる
-- 3. 以下のポリシーを追加：
--
-- SELECT (読み取り): 
--   bucket_id = 'images'
--
-- INSERT (アップロード):
--   bucket_id = 'images'
--
-- =====================================================

-- =====================================================
-- サンプルデータ（テスト用）
-- =====================================================
-- INSERT INTO posts (date, author, comment, image_url) VALUES
-- ('2024-12-25', 'father', '今日はトマトの収穫をしました。赤く熟れていて美味しそうです。', NULL),
-- ('2024-12-25', 'mother', 'キュウリがたくさん採れました！', NULL),
-- ('2024-12-24', 'father', '畑の草取りをしました。', NULL);
